### ISSUE TITLE
Exception with WebStorm 2017.3

### ISSUE THREAD

**Issue by chrkv** [vkravets/FileTemplatesVariable#16]
```Component name collision: org.jetbrains.idea.project.filetemplate.PerProjectTemplateManager class org.jetbrains.idea.project.filetemplate.PerProjectTemplateManager and class org.jetbrains.idea.project.filetemplate.PerProjectTemplateManager

java.lang.Throwable: Component name collision: org.jetbrains.idea.project.filetemplate.PerProjectTemplateManager class org.jetbrains.idea.project.filetemplate.PerProjectTemplateManager and class org.jetbrains.idea.project.filetemplate.PerProjectTemplateManager
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.b(ComponentManagerImpl.java:420)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.access$300(ComponentManagerImpl.java:56)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:483)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:118)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:102)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:89)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:284)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:289)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.b(ProjectManagerImpl.java:560)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:232)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:171)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:158)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:587)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:327)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vkravets** [comment]
Should be fixed with the latest version.
0.4.5 - fix this error
0.5.0 - align with new Jetbrains Platform API
